# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 681e85d32aac537a2d4ce589ff3220532ffe635f9a6066760d63713f27d7a254cbf4c16187c8264c412b09776eac1f5e5a0ec58c141b58a60faa3f59730acd06

test:
  secret_key_base: 05b0b6afd8a24cec7b6765168ff6e46a8ba293f73265d56b27c4145a445467907f83a1aa7bdad8f2a14fe4101effbda562b624dc65b65fe126d02fb877340496

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
